import Head from 'next/head';
import Image from 'next/image';
import Hero from '@/components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>San Robinson</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero 
      heading='San Robinson' 
      message="Welcome to my website! Here, you will find information about my experience as a software engineer and my passion for technology and problem-solving."
      mission="My mission is to be a catalyst for change. I believe that technology has the power to transform lives, and I am committed to creating solutions that make a positive impact on the world. With a diverse range of skills and professional experience, I am excited to contribute to building environments and initiatives that make a difference. In addition, I am passionate about providing affordable educational resources to those living in poverty, both in my home country of Jamaica and in the United States. I aspire to be an alchemist who can turn text into things like automated robotic limbs, phone apps that allow you to order groceries to your door, or creating a pathway to accessible healthcare treatment during a pandemic." 
      meetthefounder= "Software Engineer | Technical Project Manager | Lifetime Learner"
      about= "Hi there! My name is San, and I am a project manager and full-stack developer with a passion for building and problem-solving. Ever since I was a child, I loved creating things, from furniture to environmental habitats in my backyard. As I grew older, I discovered my love for technology and operations, which only grew stronger after traveling abroad and seeing the incredible advancements that technology has made. In 2020, I took a CodeinPlace class hosted by Stanford, and since then, I completed a full-stack development bootcamp through Ada Developers Academy. I believe that technology has the power to make a real difference in the world, and I am eager to be a part of that effort."
      />
    </div>
  );
  
}